// Auto-generated by scripts/compile-website-content.cjs
export interface ServiceFaq {
  question: string;
  answer: string;
}

export interface RelatedServiceLink {
  title: string;
  href: string;
}

export interface DedicatedService {
  slug: string;
  category: 'digital-marketing' | 'calling-messaging' | 'development';
  hub: string;
  url: string;
  seoTitle: string;
  metaDescription: string;
  primaryTopic: string;
  searchIntent: string;
  canonicalTemplate: string;
  robots: string;
  primaryCtaDestination: string;
  breadcrumbs: string[];
  eyebrow: string;
  h1: string;
  displayHook: string;
  heroBody: string;
  primaryButton: string;
  secondaryLink: string;
  problemH2: string;
  problemBody: string;
  benefitsH2: string;
  benefits: string[];
  scopeH2: string;
  scope: string[];
  approachH2: string;
  approachBody: string;
  faqs: ServiceFaq[];
  relatedServices: RelatedServiceLink[];
  finalContactH2: string;
  finalContactButton: string;
}

import rawData from './servicesData.json';

export const ALL_SERVICES: DedicatedService[] = rawData.services as DedicatedService[];
export const SERVICES_BY_SLUG: Record<string, DedicatedService> = rawData.serviceMap as Record<string, DedicatedService>;

export const DIGITAL_MARKETING_SERVICES = ALL_SERVICES.filter(s => s.category === 'digital-marketing');
export const CALLING_MESSAGING_SERVICES = ALL_SERVICES.filter(s => s.category === 'calling-messaging');
export const DEVELOPMENT_SERVICES = ALL_SERVICES.filter(s => s.category === 'development');
