// Auto-generated by scripts/compile-website-content.cjs
import rawContent from './websiteContent.json';
import { DedicatedService } from './servicesData';

export * from './servicesData';

export const FULL_WEBSITE_CONTENT = rawContent;
export const HOME_CONTENT = rawContent.home;
export const SOLUTIONS_CONTENT = rawContent.solutions;
export const ALL_SERVICES_HUB_CONTENT = rawContent.allServicesHub;
export const DIGITAL_MARKETING_HUB_CONTENT = rawContent.digitalMarketingHub;
export const CALLING_MESSAGING_HUB_CONTENT = rawContent.callingMessagingHub;
export const DEVELOPMENT_HUB_CONTENT = rawContent.developmentHub;
export const ABOUT_CONTENT = rawContent.about;
export const HOW_WE_WORK_CONTENT = rawContent.howWeWork;
export const INDUSTRIES_CONTENT = rawContent.industries;
export const WORK_CONTENT = rawContent.work;
export const ENGAGEMENT_CONTENT = rawContent.engagement;
export const FAQ_CONTENT = rawContent.faq;
export const CONTACT_CONTENT = rawContent.contact;
export const INSIGHTS_CONTENT = rawContent.insights;
export const INSIGHT_ARTICLE_CONTENT = rawContent.insightArticle;
export const THANK_YOU_CONTENT = rawContent.thankYou;
